### ISSUE TITLE
How to simulate SV (insertions and deletions) with length > 50bp?

### ISSUE THREAD

**Issue by Meltpinkg** [yjx1217/simuG#14]
Hello!
According to the help page, when randomly simulateing variants, simuG can simulate SNP/Indels (1~50bp), and SVs (CNV/inversion/translocation). How can I simulate random insertions and deletions which are larger than 50bp?
Thanks!

**Comment by yjx1217** [comment]
Hi @Meltpinkg ,

Technically,  an insertion or deletion larger than 50bp will be considered as SV-level insertion or deletion, which can be simulated via CNV simulation.

Or, you can change the line 1620 of the `simuG.pl` script to replace `$indel_size=50` with `$indel_size=M`, where M can be whatever  the maximal value of the INDEL that you want to simulate.

Best,
Jia-Xing

**Comment by Meltpinkg** [comment]
Hi @yjx1217 

Thanks very much for your reply. That helps me a lot! :)

Best,
Shuqi

**Comment by yjx1217** [comment]
Great it helps! You are welcome. :-)
