### ISSUE TITLE
Why indels not in the -gene_gff?

### ISSUE THREAD

**Issue by xmy1990** [yjx1217/simuG#17]
Hi,
I use simuG to simu indels wtih below pras,

    -indel_count $indel_count \
     -ins_del_ratio 1.0 \
     -coding_partition_for_snp_simulation coding \
     -gene_gff test.gff3 

why result indels were not in test.gff3 regions,  it seemed that -coding_partition_for_snp_simulation  and -gene_gff did not work.
These two pras did not work for indels sim?

Thanks

**Comment by yjx1217** [comment]
Hello,

Yes, after double check the code, I think these two options were designed for SNP simulation only.

For your purpose, I guess the best way is to ran a first round random simulation first  to simulate random indels across the whole genome and then filter the resulting VCF file to only keep the indels that you want based on your regions of interests and then provide the filtered VCF file to simuG for a round of VCF-based simulation.

Best,
Jia-Xing
