### ISSUE TITLE
Does simuG generate paired end data?

### ISSUE THREAD

**Issue by mrpk123** [yjx1217/simuG#2]
Hi again,

This is not an issue but a query. Does simuG generate paired end data? And can i specify coverage? Also can i use targeted region? Couldn't find answers to these questions in your manual.

Regards
Mrinal

**Comment by yjx1217** [comment]
Hi Mrinal,

I guess my reply to your first question should answer this question as well. Please check it out. :-)

Best,
Jia-Xing

**Comment by mrpk123** [comment]
Hi Jia-Xing,

Yes, it did 😊

Thanks
Mrinal
