### ISSUE TITLE
Uncertainty in description

### ISSUE THREAD

**Issue by asan-emirsaleh** [yjx1217/simuG#7]
Hello!
You have done a great job!
Please take a look at the description of `-indel_size_powerlaw_constant` option. It seems for you to forget to change the description after copying from previous one.

Best regards
Asan

**Comment by yjx1217** [comment]
Dear Asan,

Thanks for noticing this omit! I've now fixed this issue in both README.md and simuG.pl. The description for this option now reads as follows:

```
-indel_size_powerlaw_constant
            Specify the exponent factor constant (C) for power-law-fitted indel
            size distribution: p = C * (size) ** (alpha) for size >= 1 &
            size <= 50. Default = 0.5. Example:
            -indel_size_powerlaw_constant 0.5.
```
