### ISSUE TITLE
Multicore execution

### ISSUE THREAD

**Issue by asan-emirsaleh** [yjx1217/simuG#8]
Do you plan to introduce the parallel multiprocessing functionality to simuG?
It worked in single core while I used it.

**Comment by yjx1217** [comment]
Hi Asan,

It will definitely be helpful but I am currently preoccupied by other projects. A quick workaround could be partitioning your input genomes into different subsets and use tools such as `GNU parallel` to launch multiple simuG runs.

Best,
Jia-Xing
